import { useEffect, useMemo, useState } from 'react'
import { closestCorners, DndContext, DragOverlay, KeyboardSensor, PointerSensor, useDroppable, useDraggable, useSensor, useSensors } from '@dnd-kit/core'
import type { DragEndEvent } from '@dnd-kit/core'
import { CSS } from '@dnd-kit/utilities'
import { differenceInCalendarDays, format } from 'date-fns'
import { Archive, BriefcaseBusiness, Check, ChevronDown, Download, ExternalLink, FileUp, GripVertical, Kanban, Moon, Plus, Search, Sun, Trash2, Undo2, X } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { STATUS_COLUMNS, today } from './lib/constants'
import { normalizeImported, validateDraft, type FormErrors } from './lib/validation'
import { useJobsStore } from './store/jobsStore'
import type { Job, JobDraft, JobStatus } from './types/job'
import './App.css'

const emptyDraft: JobDraft = { company: '', role: '', dateApplied: today(), status: 'wishlist', resumeUsed: '', linkedinUrl: '', salaryRange: '', notes: '', contactName: '', followUpDate: '', priority: 'medium', tags: [] }

function JobCard({ job, onEdit, onDelete }: { job: Job; onEdit: (job: Job) => void; onDelete: (job: Job) => void }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: job.id, data: { job } })
  const days = differenceInCalendarDays(new Date(), new Date(job.dateApplied))
  return <article ref={setNodeRef} style={{ transform: CSS.Translate.toString(transform) }} className={`job-card ${isDragging ? 'dragging' : ''} ${job.status === 'applied' && days > 14 ? 'stale' : ''}`} onDoubleClick={() => onEdit(job)}>
    <div className="card-top"><button className="drag-handle" aria-label={`Drag ${job.company}`} {...listeners} {...attributes}><GripVertical size={15} /></button><span className="card-date">{format(new Date(job.dateApplied), 'MMM d')}</span></div>
    <button className="card-title" onClick={() => onEdit(job)}>{job.company}</button><p className="card-role">{job.role}</p>
    <div className="card-meta">{job.resumeUsed && <span className="pill">{job.resumeUsed}</span>}<span className="days">{days === 0 ? 'Applied today' : `${days}d since applied`}</span></div>
    <div className="card-footer">{job.linkedinUrl ? <a className="icon-button" href={job.linkedinUrl} target="_blank" rel="noreferrer" aria-label="Open LinkedIn profile"><ExternalLink size={14} /></a> : <span />}{job.priority === 'high' && <span className="priority">High priority</span>}<button className="delete-button" aria-label={`Delete ${job.company}`} onClick={() => onDelete(job)}><Trash2 size={14} /></button></div>
  </article>
}

function Column({ status, jobs, onEdit, onDelete }: { status: typeof STATUS_COLUMNS[number]; jobs: Job[]; onEdit: (job: Job) => void; onDelete: (job: Job) => void }) {
  const { setNodeRef, isOver } = useDroppable({ id: status.id })
  const weekCount = jobs.filter((job) => differenceInCalendarDays(new Date(), new Date(job.dateApplied)) < 7).length
  return <section className={`column ${isOver ? 'column-over' : ''}`} ref={setNodeRef} style={{ '--accent': status.accent, '--soft': status.soft } as React.CSSProperties}>
    <header className="column-header"><div><span className="status-dot" /><span className="column-label">{status.label}</span><span className="count-chip">{jobs.length}</span></div><span className="column-week">{weekCount ? `+${weekCount} this week` : 'quiet week'}</span></header>
    <div className="column-progress"><span style={{ width: `${Math.min(100, jobs.length * 12)}%` }} /></div>
    <div className="column-list">{jobs.length ? jobs.map((job) => <JobCard key={job.id} job={job} onEdit={onEdit} onDelete={onDelete} />) : <div className="empty-column"><Archive size={18} /><span>No jobs here yet</span><small>Drag a card here or add one</small></div>}</div>
  </section>
}

function FormPanel({ job, onClose, onSave }: { job?: Job; onClose: () => void; onSave: (draft: JobDraft) => void }) {
  const history = [...new Set(useJobsStore((state) => state.jobs).map((item) => item.resumeUsed).filter(Boolean))] as string[]
  const [form, setForm] = useState<JobDraft>(job ? { ...emptyDraft, ...job } : emptyDraft)
  const [errors, setErrors] = useState<FormErrors>({})
  const update = (key: keyof JobDraft, value: string | undefined) => setForm((current) => ({ ...current, [key]: value }))
  const submit = (event: React.FormEvent) => { event.preventDefault(); const nextErrors = validateDraft(form); setErrors(nextErrors); if (!Object.keys(nextErrors).length) onSave(form) }
  return <motion.aside initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} className="form-panel"><div className="panel-heading"><div><span className="eyebrow">{job ? 'Edit record' : 'New opportunity'}</span><h2>{job ? 'Update job' : 'Add a job'}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close form"><X /></button></div>
    <form onSubmit={submit} className="job-form"><label>Company<input autoFocus value={form.company} onChange={(e) => update('company', e.target.value)} placeholder="Acme, Inc." />{errors.company && <em>{errors.company}</em>}</label><label>Role<input value={form.role} onChange={(e) => update('role', e.target.value)} placeholder="Senior Product Designer" />{errors.role && <em>{errors.role}</em>}</label><div className="form-grid"><label>Date applied<input type="date" value={form.dateApplied} onChange={(e) => update('dateApplied', e.target.value)} /></label><label>Status<select value={form.status} onChange={(e) => update('status', e.target.value as JobStatus)}>{STATUS_COLUMNS.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div><label>LinkedIn URL<input value={form.linkedinUrl ?? ''} onChange={(e) => update('linkedinUrl', e.target.value)} placeholder="https://linkedin.com/..." />{errors.linkedinUrl && <em>{errors.linkedinUrl}</em>}</label><label>Resume used<input list="resume-history" value={form.resumeUsed ?? ''} onChange={(e) => update('resumeUsed', e.target.value)} placeholder="Product design resume" /><datalist id="resume-history">{history.map((item) => <option key={item} value={item} />)}</datalist></label><div className="form-grid"><label>Salary range<input value={form.salaryRange ?? ''} onChange={(e) => update('salaryRange', e.target.value)} placeholder="$140k - $170k" /></label><label>Priority<select value={form.priority ?? 'medium'} onChange={(e) => update('priority', e.target.value as JobDraft['priority'])}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div><label>Contact name<input value={form.contactName ?? ''} onChange={(e) => update('contactName', e.target.value)} placeholder="Optional" /></label><label>Notes<textarea rows={4} value={form.notes ?? ''} onChange={(e) => update('notes', e.target.value)} placeholder="What makes this opportunity interesting?" /></label><div className="panel-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button type="submit" className="primary-button"><Check size={16} />{job ? 'Save changes' : 'Add job'}</button></div></form>
  </motion.aside>
}

function App() {
  const { jobs, loading, load, add, update, move, remove, restore, importJobs } = useJobsStore()
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState<JobStatus | 'all'>('all'); const [sort, setSort] = useState('newest'); const [panel, setPanel] = useState<'add' | Job | null>(null); const [theme, setTheme] = useState(() => localStorage.getItem('job-theme') || (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')); const [undoJob, setUndoJob] = useState<Job>(); const [activeJob, setActiveJob] = useState<Job>()
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }), useSensor(KeyboardSensor))
  useEffect(() => { void load() }, [load]); useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('job-theme', theme) }, [theme])
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setPanel('add') } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [])
  const visible = useMemo(() => jobs.filter((job) => (filter === 'all' || job.status === filter) && `${job.company} ${job.role}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'company' ? a.company.localeCompare(b.company) : sort === 'oldest' ? a.dateApplied.localeCompare(b.dateApplied) : b.dateApplied.localeCompare(a.dateApplied)), [jobs, filter, query, sort])
  const stats = useMemo(() => ({ total: jobs.length, response: jobs.length ? Math.round((jobs.filter((job) => ['interview', 'offer'].includes(job.status)).length / jobs.length) * 100) : 0, offers: jobs.filter((job) => job.status === 'offer').length }), [jobs])
  const save = async (draft: JobDraft) => { if (panel && typeof panel === 'object') await update(panel.id, draft); else await add(draft); setPanel(null) }
  const deleteJob = async (job: Job) => { await remove(job.id); setUndoJob(job); window.setTimeout(() => setUndoJob((current) => current?.id === job.id ? undefined : current), 5000) }
  const onDrop = async ({ active, over }: DragEndEvent) => { setActiveJob(undefined); if (!over) return; const destination = STATUS_COLUMNS.some((item) => item.id === over.id) ? over.id as JobStatus : jobs.find((job) => job.id === over.id)?.status; if (destination && jobs.find((job) => job.id === active.id)?.status !== destination) await move(String(active.id), destination) }
  const exportData = () => { const blob = new Blob([JSON.stringify(jobs, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `job-tracker-${today()}.json`; link.click(); URL.revokeObjectURL(link.href) }
  const importData = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = async () => { try { const incoming = normalizeImported(JSON.parse(String(reader.result))); const replace = window.confirm('Replace existing jobs? Choose Cancel to merge.'); await importJobs(incoming, replace ? 'replace' : 'merge') } catch { window.alert('That file is not a valid job export.') } }; reader.readAsText(file); event.target.value = '' }
  if (loading) return <div className="loading-screen"><div className="loading-mark"><Kanban /></div><p>Opening your workspace...</p></div>
  return <div className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark"><BriefcaseBusiness size={17} /></div><div><strong>Career board</strong><span>Local workspace</span></div></div><div className="search-wrap"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search companies or roles..." /><kbd>⌘ K</kbd></div><div className="top-actions"><button className="icon-button desktop-only" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} aria-label="Toggle theme">{theme === 'dark' ? <Sun size={17} /> : <Moon size={17} />}</button><button className="icon-button desktop-only" onClick={exportData} aria-label="Export jobs"><Download size={17} /></button><label className="icon-button desktop-only" aria-label="Import jobs"><FileUp size={17} /><input hidden type="file" accept="application/json" onChange={importData} /></label><button className="primary-button add-button" onClick={() => setPanel('add')}><Plus size={17} />Add job</button></div></header>
    <main><section className="intro-row"><div><span className="eyebrow">Your pipeline</span><h1>Make the next move.</h1><p>Keep every opportunity in view, from first spark to signed offer.</p></div><div className="stats"><div><span>All applications</span><strong>{stats.total}</strong></div><div><span>Response rate</span><strong>{stats.response}%</strong></div><div><span>Offers</span><strong className="offer-stat">{stats.offers}</strong></div></div></section><div className="toolbar"><div className="filters"><button className={filter === 'all' ? 'filter active' : 'filter'} onClick={() => setFilter('all')}>All <b>{jobs.length}</b></button>{STATUS_COLUMNS.map((item) => <button key={item.id} className={filter === item.id ? 'filter active' : 'filter'} onClick={() => setFilter(item.id)}><span style={{ background: item.accent }} />{item.label}</button>)}</div><label className="sort-select"><span>Sort</span><select value={sort} onChange={(e) => setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="company">Company A-Z</option></select><ChevronDown size={14} /></label></div><DndContext sensors={sensors} collisionDetection={closestCorners} onDragStart={({ active }) => setActiveJob(jobs.find((job) => job.id === active.id))} onDragEnd={onDrop} onDragCancel={() => setActiveJob(undefined)}><div className="board">{STATUS_COLUMNS.map((status) => <Column key={status.id} status={status} jobs={visible.filter((job) => job.status === status.id)} onEdit={setPanel} onDelete={deleteJob} />)}</div><DragOverlay>{activeJob ? <JobCard job={activeJob} onEdit={() => undefined} onDelete={() => undefined} /> : null}</DragOverlay></DndContext></main>
    <AnimatePresence>{panel && <div className="panel-backdrop" onClick={(event) => event.target === event.currentTarget && setPanel(null)}><FormPanel job={typeof panel === 'object' ? panel : undefined} onClose={() => setPanel(null)} onSave={save} /></div>}</AnimatePresence>{undoJob && <div className="undo-toast"><span><Trash2 size={15} />Deleted {undoJob.company}</span><button onClick={async () => { await restore(undoJob); setUndoJob(undefined) }}><Undo2 size={15} />Undo</button></div>}
  </div>
}

export default App
